name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  EXPO_PUBLIC_OPENAI_API_KEY: ${{ secrets.EXPO_PUBLIC_OPENAI_API_KEY }}
  EAS_TOKEN: ${{ secrets.EAS_TOKEN }}

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test

      - name: Type check
        run: npx tsc --noEmit

      - name: Expo Doctor
        run: npx expo-doctor

  preview-build:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - name: Skip preview build (missing token)
        if: ${{ env.EAS_TOKEN == '' }}
        run: echo "EAS_TOKEN not set; skipping preview build job."

      - name: Checkout
        if: ${{ env.EAS_TOKEN != '' }}
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: ${{ env.EAS_TOKEN != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        if: ${{ env.EAS_TOKEN != '' }}
        run: npm ci

      - name: Setup Expo
        if: ${{ env.EAS_TOKEN != '' }}
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          expo-version: latest
          token: ${{ secrets.EAS_TOKEN }}

      - name: Queue Android preview build
        if: ${{ env.EAS_TOKEN != '' }}
        run: npx eas build --platform android --profile preview --non-interactive --no-wait
